### ISSUE TITLE
Deploying Chalice app as non- root user

### ISSUE THREAD

**Issue by jhw** [aws/chalice#852] opened 2018-05-23 12:07 UTC
Hi,

We have a group AWS account with a root user and several non- root users. We want the non- root users to be able to deploy Chalice functions to the group account. Trying this with a "standard" `chalice deploy` we get the following -

```
An error occurred (AccessDenied) when calling the CreateRole operation: User: 
 arn:aws:iam::261572527505:user/Ashley is not authorized to perform: 
 iam:CreateRole on resource: arn:aws:iam::261572527505:role/aws_hello_world-dev
```
OK, so we figured this user didn't have sufficient permissions. We created a `Lambdas` group, added the user and gave the group `LambdaFullAccess` role, The user then changed the following in `config.json`

- manage_iam_role: false
- iam_role_arn: #{iam_role_arn}

Try again with `chalice deploy`. This time -

``` 
An error occurred (AccessDeniedException) when calling the ImportRestApi 
 operation: User: arn:aws:iam::261572527505:user/Ashley is not authorized to 
 perform: apigateway:POST on resource: arn:aws:apigateway:eu-west-1::/restapis
```

 Ho hum. Added `AmazonAPIGatewayInvokeFullAccess` to the group permissions on the server side. No change. Tried using `manage_iam_role: true`; still no change.

At this point we figure we are just on the wrong track. Apologies if these are terrible noob questions - we like Chalice but AWS permissioning is a nightmare - but -

- are we on the right track here, modifying IAM roles on the server side ? Or do we need to make some changes to `policy-dev.json` ?
- if the former, what is the full list of roles that is required to make this work ? If the latter, what should we be adding to `policy-dev.json` ? Should we be modifying `iam_role_arn` ?

Confused :-/

**Comment by kadrach** [comment] 2018-05-23 22:58
There are two different things at play here:
- Deploy-time permissions needed by the deploying IAM principal (e.g. IAM user jhw)
- Run-time permissions required for the Chalice app. `manage_iam_role` and `iam_role_arn` affect this. If you set neither, Chalice will attempt to deploy a generated IAM role at deploy time, requiring additional permissions for the IAM principal (see above)

I'm not sure if this is documented, I can't find it at a quick glance. Some example policies [here](https://github.com/aws/chalice/issues/59), I've not tested them.

**Comment by stealthycoin** [comment] 2018-05-24 22:11
@jhw @kadrach is correct. And they are currently not documented. I'd suggest if you want to get this updated to go and thumbs up the documentation thread that @kadrach linked. I'm going to close this as a duplicate of that one in the meantime.

**Closed by stealthycoin** 2018-05-24 22:11 UTC
