### ISSUE TITLE
API Gateway name of deployed stage

### ISSUE THREAD

**Issue by raygers** [aws/chalice#941] opened 2018-08-28 07:33 UTC
Hi, is there a way to change the api gateway app name for the different stages when deploying to api gateway. When viewing the deployed api in the api gateway console, the api names are the same for both stages. I am using chalice deploy --stage dev and chalice deploy --stage prod. In the api console these are 2 api's with the same name. Can this be overcome by a configuration setting somewhere?

**Comment by dmulter** [comment] 2018-08-30 18:04
This is a duplicate of #490

**Comment by stealthycoin** [comment] 2018-09-24 22:32
@raygers - @dmulter is correct. Can you go thumbs up that other issue. We use thumbs up for prioritization.

**Closed by stealthycoin** 2018-09-24 22:32 UTC
