### ISSUE TITLE
Random errors KMSAccessDeniedException or AccessDeniedException on chalice invoke

### ISSUE THREAD

**Issue by vfilimonov** [aws/chalice#1342] opened 2020-01-18 21:13 UTC
Hello,

Sometimes after deployment the function could not be invoked and `chalice invoke -n function` results in one of two errors:
```
Error: got 'AccessDeniedException' exception back from Lambda
The role defined for the function cannot be assumed by Lambda.
```
or
```
Error: got 'KMSAccessDeniedException' exception back from Lambda
Lambda was unable to decrypt the environment variables because KMS access was denied. Please check the function's KMS key settings. KMS Exception: AccessDeniedExceptionKMS Message: The ciphertext refers to a customer master key that does not exist, does not exist in this region, or you are not allowed to access.
```
even on rather trivial ("hello-world"-like) functions.

If invoking the function via `boto3` or `awscli` or directly in the AWS console - it results in the same error.

After redeploy the issue is often goes away:
- `chalice deploy` for `AccessDeniedException` or 
- `chalice delete && chalice deploy` for `KMSAccessDeniedException`

I was trying to deduct a pattern or a cause for these errors, but unfortunately I could not find one.
Google search shows 2 related issues in other (Node.js) frameworks of AWS lambda:
- https://github.com/serverless/examples/issues/279
- https://github.com/apex/apex/issues/841

On the [serverless thread](https://github.com/serverless/examples/issues/279) the same "workarounds" are discussed and suggested that this might be an AWS bug. 

Even if it is the bug from AWS, filing this issue (and hopefully discussion: any idea/help beyond a bruteforce redeploy are much appreciated) might help those coming from google.

**Comment by danil-smirnov** [comment] 2020-01-18 21:20
Duplicate of #1103

**Comment by vfilimonov** [comment] 2020-01-18 21:22
oops, I'm sorry - the search did not reveal that one (maybe because of not exact match in error names)

**Comment by jamesls** [comment] 2020-02-24 21:11
Closing as dupe, let's track this work over at #1103 .  Still not sure what our best option to handle this would be.

**Closed by jamesls** 2020-02-24 21:11 UTC
