### ISSUE TITLE
.chalice/policy.json not generated for s3 event lambda

### ISSUE THREAD

**Issue by lesatdgl** [aws/chalice#985] opened 2018-11-14 22:43 UTC
chalice 1.6.1 docs
"Whenever your application is deployed using chalice, the auto generated policy is written to disk at <projectdir>/.chalice/policy.json. When you run the chalice deploy command, you can also specify the --no-autogen-policy option. Doing so will result in the chalice CLI loading the <projectdir>/.chalice/policy.json file and using that file as the policy for the IAM role. You can manually edit this file and specify --no-autogen-policy if you’d like to have full control over what IAM policy to associate with the IAM role."
I've deployed the sample S3 event code - it works! 
I then added code to read the file that triggered the event - it fails with 400
I looked at permissions on the lambda and they have only CreateLogs...
OK, so I went to .chalice/policy.json to edit and continue and found (or rather) didn't find it

[chalice-tree.zip](https://github.com/aws/chalice/files/2582936/chalice-tree.zip)

**Comment by kyleknap** [comment] 2019-01-08 23:08
Hi @lesatdgl. Could you share the code that you deployed that does not work and the exact commands you ran? It is a little difficult to tell what the issue is.

Also in general, the S3 event permissions will not be in the `policy.json`. This is done via the [AddPermission API call](https://botocore.amazonaws.com/v1/documentation/api/latest/reference/services/lambda.html#Lambda.Client.add_permission) which is probably why you are only seeing the `CreateLogs` permissions.

**Comment by lesatdgl** [comment] 2019-01-09 18:55
Thanks for the response! 
Here's the whole mess - the .zip contains the project dir in a pipenv 
There are two projects - helloWorld (your example) and s3event (the one in question)

From your note, it seems that that problem is documentation rather than code???
[chalice-projects.zip](https://github.com/aws/chalice/files/2742182/chalice-projects.zip)

**Comment by kyleknap** [comment] 2019-01-11 21:54
Thanks for the zip that definitely helps. The problem was that the resource interface was being used. For the automatic IAM policy generator it only supports client methods. So I updated the code to the following and got it to work (note you will have to change the bucket name back):
```python
from chalice import Chalice

import boto3
import os

app = Chalice(app_name='s3Event')

app.debug = True

s3 = boto3.client('s3')


@app.on_s3_event(bucket='mybucket',
                 events=['s3:ObjectCreated:*'])
def handle_s3_event(event):
    app.log.debug("Received event for bucket: %s, key: %s",
                  event.bucket, event.key)
    fn = os.path.split(event.key)[1]       # just the filename
    print('>>>fn: {} event.bucket: {} event.key: {}'.format(
            fn, event.bucket, event.key)
          )
    filename = '/tmp/' + fn
    s3.download_file(event.bucket, event.key, filename)
    with open(filename) as f:
        for line in f:
            print(line)

```
Let us know if that works for you!

**Comment by lesatdgl** [comment] 2019-01-11 23:30
Awesome! I'll try it this weekend

**Comment by stealthycoin** [comment] 2019-01-31 23:54
Closing since it looks like this is resolved. Reopen if its still an issue.

**Closed by stealthycoin** 2019-01-31 23:54 UTC
