### ISSUE TITLE
Support Lambda Functions powered by Graviton2 processor

### ISSUE THREAD

**Issue by jaga810** [aws/chalice#1812] opened 2021-10-05 01:56 UTC
Support Lambda Functions powered by Graviton2 processor as SAM and CDK do to optimize cost.
https://aws.amazon.com/jp/blogs/aws/aws-lambda-functions-powered-by-aws-graviton2-processor-run-your-functions-on-arm-and-get-up-to-34-better-price-performance/

**Comment by jamesls** [comment] 2021-10-05 16:52
Dupe of https://github.com/aws/chalice/issues/1808.  I think we can start with just plumbing the config value through, but there will need to be some work on the packager to attempt to download/build ARM binary packages.

**Closed by jamesls** 2021-10-05 16:52 UTC
