### ISSUE TITLE
Bug: `chalice deploy` fails to discover required permissions for Lambda IAM role

### ISSUE THREAD

**Issue by mileserickson** [aws/chalice#692] opened 2018-01-24 20:24 UTC
Ordinarily, `chalice deploy` finds IAM permissions required for the application to work, builds an IAM role and prompts the user for authorization to add necessary permissions to the role:

```
$ chalice deploy
Regen deployment package.

The following actions will be added to the execution policy:

s3:GetObject

Would you like to continue?  [Y/n]:
```

However, in some situations, the required permissions are not discovered and the app is deployed without the required permissions, resulting in botocore.exceptions.ClientError (AccessDenied) when a request is received.

In the example below, the app is deployed with a role that is missing the permissions that it requires.

### MVCE
**app.py:**
```
import boto3
from chalice import Chalice

app = Chalice(app_name='bug')
s3 = boto3.client('s3')
app.debug = True


@app.route('/')
def index():
    data = get_content('foo')
    return {'data': data.decode()}


def get_content(key):
    content = s3.get_object(Bucket='this-chalice-resembles-a-grail',
                            Key=key)['Body'].read()
    return content
```

**Comment by kyleknap** [comment] 2018-01-24 20:39
I can confirm as well. I was even just doing this:
```python
from chalice import Chalice
import boto3

app = Chalice(app_name='pycascades')
ec2 = boto3.client('ec2')


@app.route('/')
def index():
    return get_regions()


def get_regions():
    return ec2.describe_regions()
```
I get prompted correctly for policy generation for this though:
```python
from chalice import Chalice
import boto3

app = Chalice(app_name='pycascades')
ec2 = boto3.client('ec2')


@app.route('/')
def index():
    return ec2.describe_regions()
```

**Comment by weilu** [comment] 2018-04-10 17:07
It looks like `s3.upload_file` is not detected at all even if it's in `index()`. Is there a workaround in the meantime? Because as it is now, even when I edit the policy manually, the next deployment will prompt me to overwrite it and there doesn't seem to be a way to skip the overwrite.

**Comment by mileserickson** [comment] 2018-04-10 23:15
@weilu You can specify a role manually and tell Chalice to stop overwriting it.

Here's an example `.chalice/config.json` file:
```json
{
  "version": "2.0",
  "app_name": "example-app",
  "manage_iam_role": false,
  "iam_role_arn": "arn:aws:iam::424242424242:role/service-role/S3_read_access",
  "stages": {
    "dev": {
      "api_gateway_stage": "api"
    }
  }
}
```

**Comment by GergelyM** [comment] 2018-10-03 18:07
We had the same issue with Chalice. It didn't discover all required permission. We spent a fair amount of time testing different ideas and suggestions. We were not able to get Chalice to cover all permissions. And also the manual policy cration is not a viable option for our purpose. 

Finally I found a workaround that did the trick for us. But be warend: **it is very ugly** :)

We handpicked all the boto3.client('s3') functions we need/call in the API.    
And created a dummy function like
```python
def dummy():
    """
    Collection of all s3.client() functions.
    The sole purpose is to force Chalice to generate the right permissions in the policy.
    Does nothing and returns nothing.
    """
    s3 = boto3.client('s3')
    s3.put_object()
    s3.download_file()
    s3.get_object()
    s3.list_objects_v2()
    s3.get_bucket_location()
```


Then "call" the dummy in the root route, and make sure it will never be called, like:
```python
@app.route('/')
def index():
   _DUMMY = False
    if _DUMMY:
        dummy()
    ...
```

Without changing any settings in the config, all required permission magically appeared in the autogenerated policy after deploy.

```json
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Action": [
        "s3:GetBucketLocation",
        "s3:GetObject",
        "s3:ListBucket",
        "s3:PutObject"
      ],
      "Resource": [
        "*"
      ],
      "Sid": "..."
    }
  ]
}
```

**Comment by johntmyers** [comment] 2019-08-24 00:55
> @weilu You can specify a role manually and tell Chalice to stop overwriting it.
> 
> Here's an example that may help with editing your `.chalice/config.json` file:
> 
> ```json
> {
>   "version": "2.0",
>   "app_name": "example-app",
>   "manage_iam_role": false,
>   "iam_role_arn": "arn:aws:iam::424242424242:role/service-role/S3_read_access",
>   "stages": {
>     "dev": {
>       "api_gateway_stage": "api"
>     }
>   }
> }
> ```
> 
> Replace `424242424242` with your account number.
> Replace `S3_read_access` with your service role name.
> Replace `example-app` with your app name.
> 
> When `manage_iam_role` is set to `false`, Chalice will not auto-generate a new role.

This role has to be a different role though, right? Saying I want to keep the current role but just stop updating it is not an option. When I set the this in my config, Chalice fails to deploy because it cannot delete the current role (the one I want to keep but not update). Of course it cannot delete the role because there are policies attached to it.

**Comment by kucharzyk-sebastian** [comment] 2020-05-09 13:12
Hello. It's been over 2 years since the bug was reported. Do you have any ETA for the fix or do we still need to use workarounds?

**Comment by KeynesYouDigIt** [comment] 2021-01-20 00:37
Bumping this. We have a scenario where we are configuring a few different things when the app starts up, including fetching the name of a resource. The endpoint can't seem to figure out that it needs the access to do that....

**Comment by jamesls** [comment] 2021-01-29 17:48
Fixed via https://github.com/aws/chalice/pull/1628

**Closed by jamesls** 2021-01-29 17:48 UTC
Labels: bug

**Comment by mcchong** [comment] 2021-03-19 20:08
Still seem to be running into this issue with `chalice 1.22.2, python 3.6.9, linux 4.15.0-136-generic`.  Don't have a code snipped ready to publish, but chalice suddenly stopped detecting my s3 upload_file() call through boto3... Not sure why, it also seems to fail even on previous commits where it had been working.  Seems like there is a cache somewhere I need to clear?

**Comment by mcchong** [comment] 2021-03-22 14:47
Seems like chalice won't detect s3 permissions if you use a factory method with a global variable for injecting a stub, like in the last example here: https://aws.amazon.com/blogs/developer/introducing-the-new-test-client-for-aws-chalice/.

**Comment by mjohnson159** [comment] 2021-09-11 00:45
> We had the same issue with Chalice. It didn't discover all required permissions. We spent a fair amount of time testing different ideas and suggestions. We were not able to get Chalice to cover all permissions. And also the manual policy creation is not a viable option for our purpose.
> 
> Finally, I found a workaround that did the trick for us. But be warned: **it is very ugly** :)
> 
> We handpicked all the boto3.client('s3') functions we need/call in the API.
> And created a dummy function like
> 
> ```python
> def dummy():
>     """
>     Collection of all s3.client() functions.
>     The sole purpose is to force Chalice to generate the right permissions in the policy.
>     Does nothing and returns nothing.
>     """
>     s3 = boto3.client('s3')
>     s3.put_object()
>     s3.download_file()
>     s3.get_object()
>     s3.list_objects_v2()
>     s3.get_bucket_location()
> ```
> 
> Then "call" the dummy in the root route, and make sure it will never be called, like:
> 
> ```python
> @app.route('/')
> def index():
>     if False:     # make this to never evaluate as True
>         dummy()
>     ...
> ```
> 
> Without changing any settings in the config, all required permission magically appeared in the autogenerated policy after deploy.
> 
> ```json
> {
>   "Version": "2012-10-17",
>   "Statement": [
>     {
>       "Effect": "Allow",
>       "Action": [
>         "s3:GetBucketLocation",
>         "s3:GetObject",
>         "s3:ListBucket",
>         "s3:PutObject"
>       ],
>       "Resource": [
>         "*"
>       ],
>       "Sid": "..."
>     }
>   ]
> }
> ```

Can confirm this is still required to get auto-gen policies to populate in September 2021 :/

We have everything for S3 and Dynamo well-defined at the top of app.py and used throughout a bunch of methods that are below index() and yet they still aren't populating (location of index() in relation to other code doesn't affect autogen policy at all). By creating this dummy() method and calling it within index() in an unreachable block, it correctly populates the required permissions. Currently, only tested and proven with S3 and Dynamo.

Unfortunately, it still doesn't seem to specify the resources that I'm including and just has "Resource": ["*"]. Is there a way to get these resources to update without including them as deployed resources via template merging/importing?

-----

Interestingly, there's also a discrepancy of the autogenerated policy output by  `chalice gen-policy` and the policy when viewing the IAM role within the IAM console. The policy includes:

```json
        {
            "Effect": "Allow",
            "Action": [
                "logs:CreateLogGroup",
                "logs:CreateLogStream",
                "logs:PutLogEvents"
            ],
            "Resource": "arn:*:logs:*:*:*"
        }
```

which is necessary and helpful, but strange that it isn't included in the CLI output.
