### ISSUE TITLE
Chalice Auto Policy Generation not working for boto3's resources (OOP interface)

### ISSUE THREAD

**Issue by budowski** [aws/chalice#690] opened 2018-01-22 23:53 UTC
Chalice doesn't detect and generate the appropriate IAM roles for S3 when encountering the following:
```python
s3 = boto3.resource('s3')
bucket = s3.Bucket('my_bucket')
for file in bucket.objects.filter(Prefix='aaa/bbb/'):
   obj = s3.Object(bucket, key)
```

In the above case, neither `s3:getObject` nor `s3:ListBucket` roles will be generated for the policy.

It does work properly when switching to statements like `boto3.client("s3")` and `s3_client.list_objects`.

**Comment by dstufft** [comment] 2018-01-26 17:27
This is a duplicate of https://github.com/aws/chalice/issues/118.

**Closed by dstufft** 2018-01-26 17:27 UTC
Labels: duplicate
