### ISSUE TITLE
Define Lambda Function VPC

### ISSUE THREAD

**Issue by mickzer** [aws/chalice#552] opened 2017-09-24 17:44 UTC
It would be nice that in the config file it was possible to define a VPC ID for the lambda function. I require this functionality to connect to some private resources in a VPC and have to manually update the VPC after chalice deploy.

**Comment by joguSD** [comment] 2017-09-25 17:08
Duplicate of #413. 
There's a PR for this in progress too: #457.

**Closed by joguSD** 2017-09-25 17:08 UTC
