### ISSUE TITLE
Feature request: Custom API Gateway and Lambda names per Chalice stage

### ISSUE THREAD

**Issue by Pe-te** [aws/chalice#1286] opened 2019-10-29 15:50 UTC
Right now the code is creating one API Gateway for each Chalice stage, which is okay.
But they all have the same name, so they are hard to distinguish (you have to go inside and check the stages).

Would be nice if we could fully customize the gateway name or at least add the stage as a suffix. (app_name + "-" + stage)

**Comment by dmulter** [comment] 2019-11-19 17:55
Duplicate of #490 ?

**Comment by Pe-te** [comment] 2019-11-20 09:07
Yeah, looks like the same, thanks!

**Closed** 2019-11-20 09:09 UTC
Labels: feature-request
