### ISSUE TITLE
EnvironmentVariablesFeature is not supported in cn-north-1 region

### ISSUE THREAD

**Issue by nooperpudd** [aws/chalice#742] opened 2018-03-12 03:16 UTC
chalice deploy
Creating role: nono-dev
Creating deployment package.
Creating lambda function: nono-dev
ERROR - While sending your chalice handler code to Lambda to create function 
"nono-dev", received the following error:

 An error occurred (InvalidParameterValueException) when calling the 
 CreateFunction operation: EnvironmentVariablesFeature is not supported in cn-
 north-1 region. For more information, please visit the AWS Lambda 
 documentation on Environment Variables.

**Comment by joguSD** [comment] 2018-03-14 00:28
Duplicate of https://github.com/aws/chalice/issues/667
Thanks for reporting.

**Closed by joguSD** 2018-03-14 00:28 UTC
