### ISSUE TITLE
Default Deploy to Failure if Vendoring fails

### ISSUE THREAD

**Issue by wollerman** [aws/chalice#959] opened 2018-10-05 18:04 UTC
Related to #928, where I was looking for an issue and overlooked the deploy because of the successful status even though vendoring failed. 

If you quickly glance at the output, it shows chalice deployed successfully even though it had output for `Could not install dependencies`. What do others think of defaulting deploy behavior to fail if either it can't install dependencies or they aren't vendored?

That would force you to acknowledge that you're ok with unvendored things or to fix the issue before it's deployed to lambda.

**Comment by kadrach** [comment] 2018-10-06 01:28
See #929

**Comment by dstufft** [comment] 2018-10-08 00:34
This appears to be a duplicate of #929, closing in favor of that issue.

**Closed by dstufft** 2018-10-08 00:34 UTC
