### ISSUE TITLE
Using on_sqs_message with a CDK created queue

### ISSUE THREAD

**Issue by dcrowe** [aws/chalice#1681] opened 2021-03-13 02:10 UTC
I'm playing with the "[CDK] Rest API with a DynamoDB table" demo project and am trying to add an SQS queue+handler to it.

I have added the queue like so:
   ```
 def _create_queue(self) -> sqs.Queue:
        the_queue = sqs.Queue(
            self, 'the_queue',
            delivery_delay=cdk.Duration.seconds(15),
        )
        cdk.CfnOutput(self, 'QueueName', value=the_queue.queue_name)
        return the_queue
```

And added the handler like so:
```
@app.on_sqs_message(queue=os.environ.get('THE_QUEUE', ''))
def the_queue_handler(event):
    app.log.info("Event: %s", event.to_dict())
    for record in event:
        app.log.info("Message body: %s", record.body)
```

The queue appears to be created correctly, but registering the EventSourceMapping fails:
```
12:19:23 pm | CREATE_FAILED        | AWS::Lambda::EventSourceMapping | HandlerHandlerSqsEventSource
Invalid request provided: Invalid event source arn: The Relative Id must be non-empty: arn:aws:sqs:ap-southeast-2:341354347128: (Service: Lambda, Status Co
de: 400, Request ID: aca69971-9c5f-4529-8182-738f1e4d044a, Extended Request ID: null)
```

Have I done something wrong?

**Comment by jamesls** [comment] 2021-04-01 20:49
Hi, sorry for the delay on this.  You also need to map an environment variable into the lambda function, similar to what's done for the DynamoDB example.  In the `./infrastructure/stacks/chaliceapp.py` file you'll also need:

```python

    def __init__(self, scope, id, **kwargs):
        super().__init__(scope, id, **kwargs)
        self.dynamodb_table = self._create_ddb_table()
        self.chalice = Chalice(
            self, 'ChaliceApp', source_dir=RUNTIME_SOURCE_DIR,
            stage_config={
                'environment_variables': {
                    'APP_TABLE_NAME': self.dynamodb_table.table_name,
                    'THE_QUEUE': the_queue.queue_url,
                }
            }
        )
        self.dynamodb_table.grant_read_write_data(
            self.chalice.get_role('DefaultRole')
        )

```

I'll update the docs with more info about this.

**Comment by dcrowe** [comment] 2021-04-04 22:32
Thanks @jamesls, I've followed your instructions but now I am getting a new error:
```
Error: Resource referenced in Fn::Sub expression with logical ID: 'Token[TOKEN' was not found in the template
```

Digging into this, this appears to be the problem line in the CFN template generated by Chalice:
```
"Fn::Sub": "arn:${AWS::Partition}:sqs:${AWS::Region}:${AWS::AccountId}:${Token[TOKEN.97]}"
```
I can see that the token substitution has worked on other lines, but I don't understand why it hasn't worked here.

**Comment by jonodrew** [comment] 2021-04-05 11:08
I've just discovered this, apparently at exactly the same time as you. It seems that the decorator is being evaluated before the Stack is generated. I tested this by hard-coding the name of the queue in the decorator and seeing that the error @dcrowe identified disappeared

**Comment by jamesls** [comment] 2021-04-05 17:08
I can confirm the behavior you're seeing.  I believe what's happening is that as part of the "import" process to bring the Chalice app into a CDK app (using CfnInclude) CDK is parsing/validating the references used in `Fn::Sub`.  In our case the environment variable is a token (e.g. `${Token[TOKEN.97]}`) that will get resolved during the synthesis process of CDK which happens *after* the CfnInclude process.  In order to get this to work we'd need CDK to not fail when it sees these token references in an `Fn::Sub` or we'd have to not use `Fn::Sub`.

I'm not sure if CDK would be willing to special case these Tokens (I'll ask), but on the Chalice side I can add a fix by allowing you to specify a `queue_arn` so we can avoid using `Fn::Sub` directly.  So you'd be able to do something like this:

```python

        self.the_queue = self._create_queue()
        self.chalice = Chalice(
            self, 'ChaliceApp', source_dir=RUNTIME_SOURCE_DIR,
            stage_config={
                'environment_variables': {
                    'APP_TABLE_NAME': self.dynamodb_table.table_name,
                    'THE_QUEUE_ARN': self.the_queue.queue_arn,
                }
            }
        )


# in app.py

@app.on_sqs_message(queue_arn=os.environ.get('THE_QUEUE_ARN', ''))
def the_queue_handler(event): ...
```

**Comment by jonodrew** [comment] 2021-04-05 18:03
Works for me

**Comment by dcrowe** [comment] 2021-04-10 09:39
Thanks. I'd be happy to provide the PR if you would like.

**Comment by pdblaszczyk** [comment] 2021-04-21 12:06
Any updates? I also keep getting an error when passing env variable from CDK to `on_sqs_message`:

```
jsii.errors.JSIIError: Resource referenced in Fn::Sub expression with logical ID: 'Token[TOKEN' was not found in the template
```

**Comment by jamesls** [comment] 2021-05-04 17:07
Added the `queue_arn` param in #1720, which will be in the next Chalice release.

**Closed** 2021-05-04 17:07 UTC
Labels: documentation
